import React from 'react';
import { useGlobalContext } from '../context/Context';


const AlertCenter = () => {
  const { user, alerts, resolveAlert } = useGlobalContext();

  const getAlertBadgeColor = (severity) => {
    switch (severity) {
      case 'Critical': return 'bg-red-100 text-red-800 border-red-200';
      case 'High': return 'bg-orange-100 text-orange-800 border-orange-200';
      case 'Medium': return 'bg-yellow-100 text-yellow-800 border-yellow-200';
      default: return 'bg-blue-100 text-blue-800 border-blue-200';
    }
  };

  const activeAlerts = alerts.filter(a => !a.resolved);

  return (
    <div className="space-y-6 animate-fadeIn">

      {/* Main Alerts Log */}
      <div className="bg-white rounded-3xl border border-slate-100 shadow-premium overflow-hidden">
        <div className="px-6 py-5 border-b border-slate-100 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 bg-white">
          <div className="space-y-0.5">
            <h3 className="text-xxs font-bold text-slate-450 uppercase tracking-wider">
              Active Operations Center Issues ({activeAlerts.length})
            </h3>
            <p className="text-xs font-bold text-slate-800">Review pending system bottlenecks, saturation, and queue anomalies</p>
          </div>
          <span className="text-xxs font-bold text-indigo-650 bg-indigo-50 px-2 py-0.5 rounded-full border border-indigo-100/40">
            {user.role} View
          </span>
        </div>

        <div className="divide-y divide-slate-50">
          {activeAlerts.length === 0 ? (
            <div className="p-12 text-center text-slate-400 italic font-bold">
              <p className="text-slate-800 text-sm">All operations running smoothly.</p>
              <p className="text-xs text-slate-450 mt-1 font-semibold">No active bottleneck or capacity alerts detected.</p>
            </div>
          ) : (
            activeAlerts.map((alert) => (
              <div key={alert._id} className="p-5 flex flex-col sm:flex-row sm:items-center justify-between gap-4 hover:bg-slate-55 transition-colors">
                <div className="flex items-start space-x-3.5">
                  <span className={`w-2 h-2 rounded-full mt-1.5 shrink-0 ${
                    alert.severity === 'Critical' 
                      ? 'bg-rose-500 animate-pulse' 
                      : alert.severity === 'High' 
                        ? 'bg-amber-500' 
                        : 'bg-yellow-500'
                  }`}></span>
                  
                  <div className="space-y-1">
                    <p className="text-xs font-bold text-slate-800 leading-tight">{alert.title}</p>
                    <div className="flex flex-wrap gap-2 items-center text-[10px] font-bold text-slate-400">
                      <span className={`px-2 py-0.5 rounded-full border ${getAlertBadgeColor(alert.severity)}`}>
                        {alert.severity} Severity
                      </span>
                      <span className="bg-slate-50 text-slate-500 px-2 py-0.5 rounded-full border border-slate-100">
                        {alert.type}
                      </span>
                      <span className="text-slate-450 font-bold">
                        {new Date(alert.createdAt).toLocaleString()}
                      </span>
                    </div>
                  </div>
                </div>

                {/* Only Management can acknowledge/resolve alerts */}
                {user.role === 'Management' && (
                  <button
                    onClick={() => resolveAlert(alert._id)}
                    className="px-4 py-2 bg-emerald-50 hover:bg-emerald-100 text-emerald-800 border border-emerald-100/40 rounded-xl text-xs font-bold transition-all flex items-center justify-center cursor-pointer shrink-0 shadow-xxs active:scale-95"
                  >
                    Acknowledge
                  </button>
                )}
              </div>
            ))
          )}
        </div>
      </div>

      {/* Guidelines info card */}
      <div className="bg-slate-55 border border-slate-100 p-5 rounded-3xl flex items-start text-xs text-slate-600 leading-relaxed font-bold">
        <div className="space-y-1">
          <p className="text-slate-800 text-[11px] uppercase tracking-wider font-extrabold">Alert Center Routing Policies:</p>
          <p className="text-xxs leading-relaxed mt-1">
            Alerts are auto-generated by the system when resource parameters drift from healthy bounds. Visibility is scoped strictly for security: Management sees all warnings; Doctors see clinical-related bottlenecks; Nurses see ward bed & consumable shortages.
          </p>
        </div>
      </div>

    </div>
  );
};

export default AlertCenter;

