import React from 'react';
import { useGlobalContext } from '../context/Context';


const AlertCenter = () => {
  const { user, alerts, resolveAlert } = useGlobalContext();

  const getAlertBadgeColor = (severity) => {
    switch (severity) {
      case 'Critical': return 'bg-red-100 text-red-800 border-red-200';
      case 'High': return 'bg-orange-100 text-orange-800 border-orange-200';
      case 'Medium': return 'bg-yellow-100 text-yellow-800 border-yellow-200';
      default: return 'bg-blue-100 text-blue-800 border-blue-200';
    }
  };

  const activeAlerts = alerts.filter(a => !a.resolved);

  return (
    <div className="space-y-6">

      {/* Main Alerts Log */}
      <div className="bg-white rounded-2xl border border-slate-100 shadow-sm overflow-hidden">
        <div className="px-6 py-4 border-b border-slate-100 flex justify-between items-center bg-slate-50/50">
          <h3 className="text-base font-bold text-slate-800 flex items-center">
            Active Optimization Issues ({activeAlerts.length})
          </h3>
          <span className="text-xs font-semibold text-slate-500">
            Filtered based on: <span className="font-extrabold text-blue-600 uppercase">{user.role} permissions</span>
          </span>
        </div>

        <div className="divide-y divide-slate-100">
          {activeAlerts.length === 0 ? (
            <div className="p-8 text-center text-slate-400 italic">
              <p className="font-bold text-slate-800 text-sm">All operations running smoothly.</p>
              <p className="text-xs text-slate-500 mt-1">No active bottleneck or capacity alerts.</p>
            </div>
          ) : (
            activeAlerts.map((alert) => (
              <div key={alert._id} className="p-5 flex flex-col sm:flex-row sm:items-center justify-between gap-4 hover:bg-slate-50/50 transition-all">
                <div className="flex items-start space-x-3.5">
                  <span className={`w-3.5 h-3.5 rounded-full mt-1.5 shrink-0 ${
                    alert.severity === 'Critical' 
                      ? 'bg-red-500 animate-ping' 
                      : alert.severity === 'High' 
                        ? 'bg-orange-500' 
                        : 'bg-yellow-500'
                  }`}></span>
                  
                  <div className="space-y-1">
                    <p className="text-sm font-bold text-slate-800 leading-tight">{alert.title}</p>
                    <div className="flex flex-wrap gap-2 items-center text-[10px] font-semibold text-slate-400">
                      <span className={`px-2 py-0.5 rounded-full border ${getAlertBadgeColor(alert.severity)}`}>
                        {alert.severity} Severity
                      </span>
                      <span className="bg-slate-100 text-slate-500 px-2 py-0.5 rounded-full border border-slate-200">
                        {alert.type}
                      </span>
                      <span className="flex items-center text-slate-400 font-medium">
                        {new Date(alert.createdAt).toLocaleString()}
                      </span>
                    </div>
                  </div>
                </div>

                {/* Only Management can acknowledge/resolve alerts */}
                {user.role === 'Management' && (
                  <button
                    onClick={() => resolveAlert(alert._id)}
                    className="sm:w-auto px-4 py-2 bg-emerald-50 hover:bg-emerald-100 text-emerald-700 rounded-xl text-xs font-bold transition-all flex items-center justify-center cursor-pointer shrink-0 border border-emerald-100"
                  >
                    <span>Acknowledge</span>
                  </button>
                )}
              </div>
            ))
          )}
        </div>
      </div>

      {/* Guidelines info card */}
      <div className="bg-blue-50/50 border border-blue-100 p-5 rounded-2xl flex items-start text-xs text-blue-800 leading-relaxed font-medium">
        <div className="space-y-1">
          <p className="font-bold text-blue-900">Alert Center Routing Policies:</p>
          <p>
            Alerts are auto-generated by the system when resource parameters drift from healthy bounds. Visibility is scoped strictly for security: Management sees all warnings; Doctors see clinical-related bottlenecks; Nurses see ward bed & consumable shortages.
          </p>
        </div>
      </div>

    </div>
  );
};

export default AlertCenter;
